#!/bin/bash
# Generate distrobox.ini from the build matrix.
#
# Exports use distrobox assemble's native exported_apps/exported_bins keys, which
# run as the invoking user after the box is created. Both need absolute paths, so
# each layer build script asserts that the paths below exist and fails the build if
# they moved. Distro packages land in /usr/bin; the ai layer pins npm's global
# prefix to /usr/local because it otherwise differs per distro.
#
# The committed file is the only output; the pre-commit hook regenerates it and
# CI fails if it drifts from the matrix.
set -euo pipefail

registry=ghcr.io/marpogaus
tag=latest
repo_root=$(git rev-parse --show-toplevel)
matrix=${repo_root}/.github/matrix.yaml
out=${repo_root}/distrobox.ini

apps_path=/usr/local/share/applications
bins_path=/usr/local/bin

if ! command -v yq >/dev/null; then
    echo "gen-distrobox-ini: yq is required (https://github.com/mikefarah/yq)" >&2
    exit 1
fi

# What each layer exports. Keep in sync with context/*/<layer>-build.sh.
layer_apps() {
    case $1 in
    emacs) echo "$apps_path"/emacs.desktop ;;
    cider) echo "$apps_path"/cider.desktop ;;
    claude-desktop) echo "$apps_path"/claude-desktop.desktop ;;
    esac
}

layer_bins() {
    case $1 in
    latex)
        local all_bins=()
        for b in biber bibtex latex latexdiff latexdiff-vc latexindent latexmk lualatex pdflatex xelatex; do
            all_bins+=("$bins_path"/"$b")
        done

        echo "${all_bins[@]}"
        ;;

    ai) echo "$bins_path"/claude "$bins_path"/opencode "$bins_path"/gemini "$bins_path"/pi ;;
    esac
}

# Read the matrix up front: a process substitution feeding the loop below would
# swallow a yq failure and silently produce an empty file.
if ! entries=$(yq -r '.[] | .["image-name"] + " " + .layers' "${matrix}"); then
    echo "gen-distrobox-ini: could not read ${matrix}" >&2
    exit 1
fi
if [ -z "${entries}" ]; then
    echo "gen-distrobox-ini: no images found in ${matrix}" >&2
    exit 1
fi

render() {
    echo "# Generated by scripts/gen-distrobox-ini.sh from .github/matrix.yaml."
    echo "# Do not edit by hand; re-run the script (pre-commit does it for you)."

    while read -r name layers; do
        apps=""
        bins=""
        for layer in ${layers//,/ }; do
            case ${layer} in
            emacs | latex | ai | cider | claude-desktop) ;;
            *)
                echo "gen-distrobox-ini: ${name} uses unknown layer '${layer}'," \
                    "add it to layer_apps/layer_bins" >&2
                return 1
                ;;
            esac
            layer_a=$(layer_apps "$layer")
            layer_b=$(layer_bins "$layer")
            [ -z "$layer_a" ] || apps="${apps:+${apps} }${layer_a}"
            [ -z "$layer_b" ] || bins="${bins:+${bins} }${layer_b}"
        done

        echo
        echo "[${name}]"
        echo "image=${registry}/${name}:${tag}"
        echo "pull=true"
        echo "replace=true"
        [ -z "$apps" ] || echo "exported_apps=${apps}"
        [ -z "$bins" ] || echo "exported_bins=${bins}"
    done <<<"${entries}"
}

# Render first, write second, so a failure leaves the committed file untouched.
rendered=$(render)
printf '%s\n' "${rendered}" >"${out}"
