name: Build and publish all container images

on:
  schedule:
  - cron: 0 7 * * *
  push:
    branches: [main, dev]
    # Publish semver tags as releases.
    tags: [v*.*.*]
     # don't rebuild if only documentation has changed
    paths-ignore: ['**.md', '**.org']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  matrix:
    name: Load build matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      include: ${{ steps.load.outputs.include }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1     # v7.0.1

    - name: Load matrix
      id: load
      run: echo "include=$(yq -o=json -I=0 '.' .github/matrix.yaml)" >>"$GITHUB_OUTPUT"

  build:
    name: Build ${{ matrix.image-name }}
    needs: matrix
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    strategy:
      matrix:
        include: ${{ fromJSON(needs.matrix.outputs.include) }}
      fail-fast: false
    uses: ./.github/workflows/build-and-publish-one-image.yml
    with:
      image-name: ${{ matrix.image-name }}
      containerfile: ./containerfiles/base.containerfile
      context: ./context/${{ matrix.context }}
      platform: linux/amd64
      free-disk-space: ${{ matrix.free-disk-space == true }}
      build-args: |
        BASE_IMAGE=${{ matrix.base-image }}
        LAYERS=${{ matrix.layers }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
